# Generated by Django 3.2.8 on 2021-10-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='weather',
            field=models.CharField(max_length=150, verbose_name='Погода'),
        ),
    ]
